
version: '3.8'
services:
#  sba:
#    container_name: sba
#    build:
#      context: .
#    ports:
#      - "8080:8080"    # App port
#      - "9010:9010"    # JMX port for VisualVM
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#      - TOMCAT_MAX_THREADS=500
#      - TOMCAT_MAX_CONNECTIONS=10000
#      - TOMCAT_ACCEPT_COUNT=200
#      - TOMCAT_CONNECTION_TIMEOUT=30000
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#          memory: "1g"
#        reservations:
#          cpus: "1"
#          memory: "512m"
#    volumes:
#      - "./docker/tmp-hprof:/tmp"
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
  k6:
    container_name: k6
    image: grafana/k6:latest
    volumes:
      - ./stress.js:/scripts/stress.js:ro
    command: run /scripts/stress.js

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

