version: '3.8'
services:
#  sba:
#    container_name: sba
#    build:
#      context: .
#    ports:
#      - "8080:8080"    # App port
#      - "9010:9010"    # JMX port for VisualVM
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - TOMCAT_MAX_THREADS=500
#      - TOMCAT_MAX_CONNECTIONS=10000
#      - TOMCAT_ACCEPT_COUNT=200
#      - TOMCAT_CONNECTION_TIMEOUT=30000
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
#      - SPRING_DATASOURCE_USERNAME=myuser
#      - SPRING_DATASOURCE_PASSWORD=secret
#      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#          memory: "1g"
#        reservations:
#          cpus: "1"
#          memory: "512m"
#    volumes:
#      - "./docker/tmp-hprof:/tmp"

#  light-message:
#    image: docker.io/library/light-message:0.0.1-SNAPSHOT
#    container_name: nsba
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
#      - SERVER_TOMCAT_THREADS_MAX=4
#      - SPRING_DATA_JPA_REPOSITORIES_BOOTSTRAP_MODE=lazy

  postgres:
    container_name: postgres
    image: 'postgres:17.2'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "2.0"



#  schema-registry:
#    image: confluentinc/cp-schema-registry:7.5.0
#    depends_on:
#      - kafka
#    environment:
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
#      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
#      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'
#      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Cổng RabbitMQ
      - "15672:15672"    # Cổng giao diện quản lý web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          memory: 512M  # Giới hạn bộ nhớ tối đa
          cpus: '1.0'   # Giới hạn sử dụng CPU (1 CPU)
        reservations:
          memory: 256M  # Bộ nhớ tối thiểu (dành cho container)
          cpus: '0.5'   # CPU tối thiểu (dành cho container)

#  k6:
#    container_name: k6
#    image: grafana/k6:latest
#    environment:
#      BASE_URL: "http://sba:8080/api/v1"
#    volumes:
#      - ./k6/:/scripts/:ro
#
#    command: run /scripts/send_message.js

#  redis:
#    image: redis:6.2
#    container_name: redis
#    ports:
#      - "6379:6379"

#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#
#  grafana:
#    image: grafana/grafana-oss:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    depends_on:
#      - prometheus
#    volumes:
#      - grafana-data:/var/lib/grafana
#      - ./docker/grafana/datasources/:/etc/grafana/provisioning/datasources/
#      - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
#      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  grafana-data:

